version: '3'
services:
  node:
    image: node:12-alpine
    tty: true
    container_name: hello-japanese-frontend
    volumes:
      - ./src:/src
    working_dir: '/src'
    ports:
      - '3000:3000'
